import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  handbookSidebar: [
    {
      type: 'link',
      href: '/',
      label: 'Welcome',
      className: 'sidebar-top-level-link',
    },
    { type: 'autogenerated', dirName: '.' },
  ],
};

export default sidebars;
