import React from 'react';
import ThemedImage from '@theme/ThemedImage';
import useBaseUrl from '@docusaurus/useBaseUrl';

/**
 * Brand-styled conceptual diagram, generated by the `diagram-maker` skill as
 * paired light + dark SVGs in `static/img/diagrams/`. Swaps the matching SVG
 * per color mode via Docusaurus ThemedImage.
 *
 * Usage in MDX:  <Diagram name="llm-inference-prefill" alt="…" />
 * expects:       static/img/diagrams/<name>.svg  and  <name>-dark.svg
 */
export default function Diagram({
  name,
  alt,
  className,
}: {
  name: string;
  alt: string;
  className?: string;
}): JSX.Element {
  return (
    <ThemedImage
      className={className}
      alt={alt}
      sources={{
        light: useBaseUrl(`/img/diagrams/${name}.svg`),
        dark: useBaseUrl(`/img/diagrams/${name}-dark.svg`),
      }}
    />
  );
}
